//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoardSorter.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Contacts
    {
        public int ContactID { get; set; }
        public string myID { get; set; }
        public string yourID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }

        public virtual List<String> newContact
        {
            get
            {
                List<String> theContacts;
                using (var db = new HoardSorterEntities())
                {
                    theContacts = db.Contacts.Where(ri => ri.myID == myID).Select(ri => ri.yourID).ToList();
                }
                return theContacts;
            }
        }
    }

}
