//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoardSorter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeckCards
    {
        public int DeckCardID { get; set; }
        public int DeckID { get; set; }
        public int CardID { get; set; }
        public int CardQty { get; set; }
    
        public virtual CardDetails CardDetails { get; set; }
        public virtual Deck Deck { get; set; }
    }
}
