//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoardSorter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deck()
        {
            
            this.DeckCards = new HashSet<DeckCards>();
        }
    
        public int DeckID { get; set; }
        public string UserID { get; set; }
        public int DeckTypeID { get; set; }
        public string DeckName { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual DeckType DeckType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeckCards> DeckCards { get; set; }
    }
}
