//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoardSorter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HoardSorterEntities : DbContext
    {
        public HoardSorterEntities()
            : base("name=HoardSorterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CardCollection> CardCollection { get; set; }
        public virtual DbSet<CardDetails> CardDetails { get; set; }
        public virtual DbSet<CardSet> CardSet { get; set; }
        public virtual DbSet<Collections> Collections { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<ColorIdent> ColorIdent { get; set; }
        public virtual DbSet<Deck> Deck { get; set; }
        public virtual DbSet<DeckCards> DeckCards { get; set; }
        public virtual DbSet<DeckType> DeckType { get; set; }
        public virtual DbSet<Rarity> Rarity { get; set; }
        public virtual DbSet<RarityIdent> RarityIdent { get; set; }
        public virtual DbSet<SetIdent> SetIdent { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<TypeIdent> TypeIdent { get; set; }
    }
}
