//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoardSorter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HoardSorterEntities : DbContext
    {
        public HoardSorterEntities()
            : base("name=HoardSorterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CardCollection> CardCollections { get; set; }
        public virtual DbSet<CardDetail> CardDetails { get; set; }
        public virtual DbSet<CardSet> CardSets { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<ColorIdent> ColorIdents { get; set; }
        public virtual DbSet<Deck> Decks { get; set; }
        public virtual DbSet<DeckCard> DeckCards { get; set; }
        public virtual DbSet<DeckType> DeckTypes { get; set; }
        public virtual DbSet<Rarity> Rarities { get; set; }
        public virtual DbSet<RarityIdent> RarityIdents { get; set; }
        public virtual DbSet<SetIdent> SetIdents { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<TypeIdent> TypeIdents { get; set; }
    }
}
