//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoardSorter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RarityIdent
    {
        public int RarityID { get; set; }
        public int CardID { get; set; }
        public int RarityIdentID { get; set; }
    
        public virtual CardDetail CardDetail { get; set; }
        public virtual Rarity Rarity { get; set; }
    }
}
